package com.example.saeed_pc.mydoctor.Accessories.Database.MyDr;

import java.io.Serializable;

/**
 * Created by SAEED-PC on 10/1/2015.
 */
public class Info_registration_MyDr implements Serializable {


    private int COLUMN_ID = 0;


    private String TABLE_REGISTRATION_ELEMENT_NAME;
    private String TABLE_REGISTRATION_ELEMENT_FAMILY;
    private String TABLE_REGISTRATION_ELEMENT_USERNAME;
    private String TABLE_REGISTRATION_ELEMENT_PASSWORD;
    private String TABLE_REGISTRATION_ELEMENT_PHONE;
    private String TABLE_REGISTRATION_ELEMENT_MAIL;
    private String TABLE_REGISTRATION_ELEMENT_AGE;
    private String TABLE_REGISTRATION_ELEMENT_SEX;
    private String TABLE_REGISTRATION_ELEMENT_RESERVE1;
    private String TABLE_REGISTRATION_ELEMENT_RESERVE2;
    private String TABLE_REGISTRATION_ELEMENT_RESERVE3;
    private String TABLE_REGISTRATION_ELEMENT_RESERVE4;
    private String TABLE_REGISTRATION_ELEMENT_RESERVE5;



    public String getTABLE_REGISTRATION_ELEMENT_RESERVE1() {
        return TABLE_REGISTRATION_ELEMENT_RESERVE1;
    }

    public void setTABLE_REGISTRATION_ELEMENT_RESERVE1(String TABLE_REGISTRATION_ELEMENT_RESERVE1) {
        this.TABLE_REGISTRATION_ELEMENT_RESERVE1 = TABLE_REGISTRATION_ELEMENT_RESERVE1;
    }

    public int getCOLUMN_ID() {
        return COLUMN_ID;
    }

    public void setCOLUMN_ID(int COLUMN_ID) {
        this.COLUMN_ID = COLUMN_ID;
    }

    public  String getTABLE_REGISTRATION_ELEMENT_NAME() {
        return TABLE_REGISTRATION_ELEMENT_NAME;
    }

    public void setTABLE_REGISTRATION_ELEMENT_NAME(String TABLE_REGISTRATION_ELEMENT_NAME) {
        this.TABLE_REGISTRATION_ELEMENT_NAME = TABLE_REGISTRATION_ELEMENT_NAME;
    }

    public  String getTABLE_REGISTRATION_ELEMENT_USERNAME() {
        return TABLE_REGISTRATION_ELEMENT_USERNAME;
    }

    public void setTABLE_REGISTRATION_ELEMENT_USERNAME(String TABLE_REGISTRATION_ELEMENT_USERNAME) {
        this.TABLE_REGISTRATION_ELEMENT_USERNAME = TABLE_REGISTRATION_ELEMENT_USERNAME;
    }

    public  String getTABLE_REGISTRATION_ELEMENT_FAMILY() {
        return TABLE_REGISTRATION_ELEMENT_FAMILY;
    }

    public void setTABLE_REGISTRATION_ELEMENT_FAMILY(String TABLE_REGISTRATION_ELEMENT_FAMILY) {
        this.TABLE_REGISTRATION_ELEMENT_FAMILY = TABLE_REGISTRATION_ELEMENT_FAMILY;
    }

    public String getTABLE_REGISTRATION_ELEMENT_PASSWORD() {
        return TABLE_REGISTRATION_ELEMENT_PASSWORD;
    }

    public void setTABLE_REGISTRATION_ELEMENT_PASSWORD(String TABLE_REGISTRATION_ELEMENT_PASSWORD) {
        this.TABLE_REGISTRATION_ELEMENT_PASSWORD = TABLE_REGISTRATION_ELEMENT_PASSWORD;
    }

    public String getTABLE_REGISTRATION_ELEMENT_PHONE() {
        return TABLE_REGISTRATION_ELEMENT_PHONE;
    }

    public void setTABLE_REGISTRATION_ELEMENT_PHONE(String TABLE_REGISTRATION_ELEMENT_PHONE) {
        this.TABLE_REGISTRATION_ELEMENT_PHONE = TABLE_REGISTRATION_ELEMENT_PHONE;
    }

    public String getTABLE_REGISTRATION_ELEMENT_MAIL() {
        return TABLE_REGISTRATION_ELEMENT_MAIL;
    }

    public void setTABLE_REGISTRATION_ELEMENT_MAIL(String TABLE_REGISTRATION_ELEMENT_MAIL) {
        this.TABLE_REGISTRATION_ELEMENT_MAIL = TABLE_REGISTRATION_ELEMENT_MAIL;
    }

    public String getTABLE_REGISTRATION_ELEMENT_AGE() {
        return TABLE_REGISTRATION_ELEMENT_AGE;
    }

    public void setTABLE_REGISTRATION_ELEMENT_AGE(String TABLE_REGISTRATION_ELEMENT_AGE) {
        this.TABLE_REGISTRATION_ELEMENT_AGE = TABLE_REGISTRATION_ELEMENT_AGE;
    }

    public String getTABLE_REGISTRATION_ELEMENT_SEX() {
        return TABLE_REGISTRATION_ELEMENT_SEX;
    }

    public void setTABLE_REGISTRATION_ELEMENT_SEX(String TABLE_REGISTRATION_ELEMENT_SEX) {
        this.TABLE_REGISTRATION_ELEMENT_SEX = TABLE_REGISTRATION_ELEMENT_SEX;
    }

    public String getTABLE_REGISTRATION_ELEMENT_RESERVE2() {
        return TABLE_REGISTRATION_ELEMENT_RESERVE2;
    }

    public void setTABLE_REGISTRATION_ELEMENT_RESERVE2(String TABLE_REGISTRATION_ELEMENT_RESERVE2) {
        this.TABLE_REGISTRATION_ELEMENT_RESERVE2 = TABLE_REGISTRATION_ELEMENT_RESERVE2;
    }

    public String getTABLE_REGISTRATION_ELEMENT_RESERVE4() {
        return TABLE_REGISTRATION_ELEMENT_RESERVE4;
    }

    public void setTABLE_REGISTRATION_ELEMENT_RESERVE4(String TABLE_REGISTRATION_ELEMENT_RESERVE4) {
        this.TABLE_REGISTRATION_ELEMENT_RESERVE4 = TABLE_REGISTRATION_ELEMENT_RESERVE4;
    }

    public String getTABLE_REGISTRATION_ELEMENT_RESERVE3() {
        return TABLE_REGISTRATION_ELEMENT_RESERVE3;
    }

    public void setTABLE_REGISTRATION_ELEMENT_RESERVE3(String TABLE_REGISTRATION_ELEMENT_RESERVE3) {
        this.TABLE_REGISTRATION_ELEMENT_RESERVE3 = TABLE_REGISTRATION_ELEMENT_RESERVE3;
    }

    public String getTABLE_REGISTRATION_ELEMENT_RESERVE5() {
        return TABLE_REGISTRATION_ELEMENT_RESERVE5;
    }

    public void setTABLE_REGISTRATION_ELEMENT_RESERVE5(String TABLE_REGISTRATION_ELEMENT_RESERVE5) {
        this.TABLE_REGISTRATION_ELEMENT_RESERVE5 = TABLE_REGISTRATION_ELEMENT_RESERVE5;
    }




}
